version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: amazon-cognito-identity-js
    versions:
    - 4.5.10
    - 4.5.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
