[build]
  command = "cd client && yarn build"
  publish = "client/dist"
[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
[[headers]]
  for = "*.(css|ico|png|svg)"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[headers]]
  for = "src.*.js"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"
[[redirects]]
  from = "api/*"
  status = 200
  to = "https://a6zs5gaxx6.execute-api.us-east-1.amazonaws.com/prod/:splat"
[[redirects]]
  from = "*"
  status = 200
  to = "/"
