name: CI
on: push

jobs:
  test:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json
          node-version-file: client/.nvmrc
      - run: npm ci
      - run: npm t
